export const API_ROUTES = {
  events: "/api/events",
  activityCalls: "/api/activity/calls",
  activityCall: "/api/activity/calls/:id",
  activitySummary: "/api/activity/summary",
  agentActiveWakes: "/api/agents/active-wakes",
  agentWorker: "/api/agents/workers/:featureId",
  agentManager: "/api/agents/manager",
  agentWake: "/api/agents/wakes/:wakeId",
  agentWakeCancel: "/api/agents/wakes/:wakeId/cancel",
  agentThread: "/api/agents/threads/:threadId",
  agentThreadForks: "/api/agents/threads/:threadId/forks",
  agentThreadMessages: "/api/agents/threads/:threadId/messages",
  agentThreadQueuedMessage: "/api/agents/threads/:threadId/queued-messages/:clientRequestId",
  agentThreadSummaryDraft: "/api/agents/threads/:threadId/summary-draft",
  agentThreadTransfers: "/api/agents/threads/:threadId/transfers",
  agentSideTransferRetarget: "/api/agents/side-transfers/:transferId/retarget",
  canvasById: "/api/canvas/:id",
  canvasAssets: "/api/canvas/:id/assets/:assetPath{.+}",
  canvasEvents: "/api/canvas/:id/events",
  featureCanvases: "/api/features/:id/canvases",
  info: "/api/info",
  memoryDreamRuns: "/api/memory/dream/runs",
  memoryDreamRun: "/api/memory/dream/runs/:id",
  memoryEntries: "/api/memory/entries",
  memoryStats: "/api/memory/stats",
  paneById: "/api/panes/:paneId",
  paneSplit: "/api/panes/:paneId/split",
  projectBranches: "/api/projects/:projectId/git/branches",
  featureChanges: "/api/features/:featureId/changes",
  featureChangesFile: "/api/features/:featureId/changes/file",
  projects: "/api/projects",
  projectAdopt: "/api/projects/adopt",
  projectReorder: "/api/projects/reorder",
  projectById: "/api/projects/:id",
  projectFeatures: "/api/projects/:projectId/features",
  projectReconcile: "/api/projects/:id/reconcile",
  sessionWindow: "/api/sessions/:sessionName/windows/:windowName",
  skills: "/api/skills",
  skillsRefresh: "/api/skills/refresh",
  state: "/api/state",
  terminal: "/api/terminal",
  tmuxSessions: "/api/tmux/sessions",
  uiLocation: "/api/ui/location",
  uiPageSummary: "/api/ui/page-summary",
  voiceWs: "/api/voice/ws",
  windowInspect: "/api/windows/inspect",
  featureById: "/api/features/:id",
  featureRestore: "/api/features/:id/restore",
  featurePin: "/api/features/:id/pin",
  featureCanvasBind: "/api/features/:id/canvas/bind",
  featurePanes: "/api/features/:id/panes",
  settingsConfig: "/api/settings/config",
  setupStatus: "/api/setup/status",
  codexAuthStart: "/api/settings/auth/codex/start",
  codexAuthStatus: "/api/settings/auth/codex/status",
  codexAuthLogout: "/api/settings/auth/codex/logout",
  settingsProviderModels: "/api/settings/providers/:providerName/models",
  storageStatus: "/api/storage",
  storageCleanup: "/api/storage/cleanup",
  workItems: "/api/work-items",
  workItem: "/api/work-items/:id",
  workItemPromote: "/api/work-items/:id/promote-to-chat"
} as const;

export const API_PATHS = {
  activityCall: (id: string) => `/api/activity/calls/${encodeURIComponent(id)}`,
  agentWorker: (featureId: string) => `/api/agents/workers/${encodeURIComponent(featureId)}`,
  agentWakeCancel: (wakeId: string) => `/api/agents/wakes/${encodeURIComponent(wakeId)}/cancel`,
  agentThread: (threadId: string) => `/api/agents/threads/${encodeURIComponent(threadId)}`,
  agentThreadForks: (threadId: string) => `/api/agents/threads/${encodeURIComponent(threadId)}/forks`,
  agentThreadMessages: (threadId: string) => `/api/agents/threads/${encodeURIComponent(threadId)}/messages`,
  agentThreadQueuedMessage: (threadId: string, clientRequestId: string) =>
    `/api/agents/threads/${encodeURIComponent(threadId)}/queued-messages/${encodeURIComponent(clientRequestId)}`,
  agentThreadSummaryDraft: (threadId: string) => `/api/agents/threads/${encodeURIComponent(threadId)}/summary-draft`,
  agentThreadTransfers: (threadId: string) => `/api/agents/threads/${encodeURIComponent(threadId)}/transfers`,
  agentSideTransferRetarget: (transferId: string) =>
    `/api/agents/side-transfers/${encodeURIComponent(transferId)}/retarget`,
  canvasById: (id: string) => `/api/canvas/${encodeURIComponent(id)}`,
  canvasAssetsBase: (id: string) => `/api/canvas/${encodeURIComponent(id)}/assets/`,
  canvasEvents: (id: string) => `/api/canvas/${encodeURIComponent(id)}/events`,
  memoryDreamRun: (id: string) => `/api/memory/dream/runs/${encodeURIComponent(id)}`,
  paneById: (paneId: string) => `/api/panes/${encodeURIComponent(paneId)}`,
  paneSplit: (paneId: string) => `/api/panes/${encodeURIComponent(paneId)}/split`,
  projectBranches: (projectId: string) =>
    `/api/projects/${encodeURIComponent(projectId)}/git/branches`,
  featureChanges: (featureId: string) =>
    `/api/features/${encodeURIComponent(featureId)}/changes`,
  featureChangesFile: (featureId: string, filePath: string) =>
    `/api/features/${encodeURIComponent(featureId)}/changes/file?path=${encodeURIComponent(filePath)}`,
  projectById: (id: string) => `/api/projects/${encodeURIComponent(id)}`,
  projectFeatures: (projectId: string) => `/api/projects/${encodeURIComponent(projectId)}/features`,
  projectReconcile: (id: string) => `/api/projects/${encodeURIComponent(id)}/reconcile`,
  sessionWindow: (sessionName: string, windowName: string) =>
    `/api/sessions/${encodeURIComponent(sessionName)}/windows/${encodeURIComponent(windowName)}`,
  featureById: (id: string) => `/api/features/${encodeURIComponent(id)}`,
  featurePin: (id: string) => `/api/features/${encodeURIComponent(id)}/pin`,
  featureCanvases: (id: string) => `/api/features/${encodeURIComponent(id)}/canvases`,
  featurePanes: (id: string) => `/api/features/${encodeURIComponent(id)}/panes`,
  settingsProviderModels: (providerName: string) =>
    `/api/settings/providers/${encodeURIComponent(providerName)}/models`,
  workItem: (id: string) => `/api/work-items/${encodeURIComponent(id)}`,
} as const;
